version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: medusa-postgres
    restart: always
    environment:
      POSTGRES_USER: medusa_user
      POSTGRES_PASSWORD: medusa_password
      POSTGRES_DB: medusa_db
    ports:
      - "5432:5432"
    volumes:
      - medusa_pgdata:/var/lib/postgresql/data

volumes:
  medusa_pgdata:
